# Generated by Django 4.2.5 on 2024-03-29 08:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_user_full_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="matrimonialprofile",
            name="current_address",
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name="matrimonialprofile",
            name="height",
            field=models.FloatField(default=0),
        ),
    ]
