# Generated by Django 4.2.5 on 2024-04-08 04:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_alter_matrimonialprofile_current_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="familydetails",
            name="marital_status",
            field=models.CharField(default="", max_length=20),
        ),
    ]
